/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package me.hanslovsky.eksif

import picocli.CommandLine
import java.util.concurrent.Callable
import kotlin.system.exitProcess

@CommandLine.Command(name = "eksif", subcommands = [PrintExif::class])
class Eksif: Callable<Int> {

    override fun call(): Int {
        return 0
    }

    companion object {
        @JvmStatic
        fun main(args: Array<String>): Unit = exitProcess(CommandLine(Eksif()).execute(*args))
    }
}
